aws:
  data_path: input_data/starter/
  role_for_trust: snowflake_role2
integration:
  name: iw2021
  arn: arn:aws:iam::415120972377:role/snowflake_role2
stage:
  name: MY_BUCKET
  bucket: testinginfinityworksaws
file_format:
  csv_file_format:
    name: CSV_FILE_FORMAT
    type: CSV
    skip_header: 1
  json_file_format:
    name: JSON_FILE_FORMAT
    type: JSON
    skip_header: 0
table:
  customers_table:
    name: customers_adam
    file_format: csv_file_format
    bucket_path: /customers
    table_cols:
      customer_id: VARCHAR(10)
      loyalty_score: INTEGER
  product_table:
    name: PRODUCTS
    file_format: csv_file_format
    bucket_path: /products
    table_cols:
      product_id: VARCHAR(10)
      product_description: VARCHAR(250)
      product_category: VARCHAR(250)
  transaction_table:
    name: TRANSACTIONS
    file_format: json_file_format
    bucket_path: transactions
    table_cols:
      transaction: VARIANT


