user: "SUNI1997"
password:XXXXXX
account: "xk87678.eu-west-1"
warehouse: "COMPUTE_WH"
authenticator: "snowflake"
database: "INFINITY_WORKS_2021_01_31"
role: "ACCOUNTADMIN"
schema: "PUBLIC"

#location of the private key if using key pair authentication
#comment out if not using key pair authentication
#This has precedence over the authenticator
#private_key= "Users/keys/ras_key.p8"
